---

docker:
  external_network_name:
  external_network_parent: # The interface the traffic will physically go through on the Docker host (https://docs.docker.com/network/macvlan/)
  internal_network_name:
  syslog_address: udp://127.0.0.1:514
  loki_url: http://127.0.0.1:3100/loki/api/v1/push
  volume_base: /mnt/cache/docker # If you'll use `/mnt/user/`, you might face issues with symlinks, for example: https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/20

lab:
  domain_name: local

unraid:
  logging_dir: # See: unraid_loki_promtail
