---
# https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: prometheus_speedtest
    image: miguelndecarvalho/speedtest-exporter:latest
    env:
      SPEEDTEST_SERVER: '{{ apps.prometheus.speedtest.server }}'
    networks:
      - name: '{{ docker.external_network_name }}'
      - name: '{{ docker.internal_network_name }}'
    extra:
      cpus: 0.5
      memory: 1G
      kernel_memory: 1G

- name: Add Speedtest to Prometheus Config
  include_tasks: '{{ playbook_dir }}/dry/prometheus-config.yml'
  vars:
    job_name: speedtest
    job:
      metrics_path: /metrics
      scrape_interval: 30m
      scrape_timeout: 60s
      static_configs:
        - targets: ["prometheus_speedtest.{{ docker.internal_network_name }}:9798"]
