---
# https://github.com/tubearchivist/tubearchivist/

# $ docker exec -it elasticsearch elasticsearch-setup-passwords interactive

- set_fact:  # noqa 502
    _name: tube
    _port: 8000

# REDIS

- include_tasks: '{{ playbook_dir }}/dry/docker/redis.yml'
  vars:
    redis_image: redislabs/rejson:latest
    redis_cmd:
      - redis-server
      - /redis/redis.conf
      - --loadmodule
      - /usr/lib/redis/modules/rejson.so
      - --loadmodule
      - /usr/lib/redis/modules/redisearch.so
    parent_container_name: '{{ _name }}'

# MAIN SERVER

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: bbilly1/tubearchivist:latest
    include_secrets: true
    icon: tubearchivist
    env:
      ES_URL: 'http://elasticsearch.{{ lab_domain_name }}:9200'
      REDIS_HOST: '{{ redis_host }}'
      REDIS_PORT: '{{ redis_port }}'
      TA_PORT: '{{ _port | string }}'
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'

    volumes:
      - [ '/uwsgi.ini', '/app/uwsgi.ini', 'ro' ]
      - [ '/cache', '/cache', 'rw' ]
      - '{{ services.tubearchivist.storage_volume }}:/youtube:rw'

    files:
      - src: uwsgi.ini
        dest: ''
        force: true

    proxy:
      - http_port: '{{ _port }}'

    extra:
      cpus: 4
      memory: 2G
      kernel_memory: 2G
