---

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install Dasel
    script: |
      cp -fv /boot/homelab/dasel_linux_amd64 /usr/bin/dasel
      chmod -v +x /usr/bin/dasel
