---

- block:
    - include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
      vars:
        name: Docker Redis
        script: '{{ settings | join("\n") }}'
      register: _redis_kernel_settings_on_boot
    - name: Optimize kernel settings for Redis
      command: '{{ item }}'
      with_list: '{{ settings }}'
      when: _redis_kernel_settings_on_boot.changed
  vars:
    settings:
      - 'sysctl -w vm.overcommit_memory=1'
      - 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled'
