---

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Tweak sysctl
    script: |-2
      # ElasticSearch
      # https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html#docker-prod-prerequisites
      sysctl -w vm.max_map_count=262144

      # Redis
      sysctl -w vm.overcommit_memory=1
      echo madvise > /sys/kernel/mm/transparent_hugepage/enabled
