---

- block:
    - include_tasks: _persistent-storage.yml

    - include_tasks: _install_dasel.yml
    - include_tasks: _install_dell_tools.yml
    - include_tasks: _log_dir_size.yml
    - include_tasks: _python-virtualenv.yml
    - include_tasks: _slow_down_fans.yml
    - include_tasks: _sysctl.yml

    - include_tasks: '{{ role_path }}/_docker_icons/task.yml'
    - include_tasks: '{{ role_path }}/_docker_webui_url/task.yml'
    - include_tasks: '{{ role_path }}/_hddtemp/task.yml'
    - include_tasks: '{{ role_path }}/_supervisor/task.yml'
    - include_tasks: '{{ role_path }}/_webhooks/task.yml'

  when: not (disable_meta_dependencies | bool | default(false))
