---

- block:
    - include_tasks: _persistent-storage.yml

    - include_tasks: _install-dasel.yml
    - include_tasks: _install-dell-tools.yml
    - include_tasks: _log-dir-size.yml
    - include_tasks: _python-virtualenv.yml
    - include_tasks: _sysctl.yml

    - include_tasks: _docker_improvements/task.yml
    - include_tasks: _hddtemp/task.yml
    - include_tasks: _webhooks/task.yml

    - include_tasks: _zfs/task.yml

  when: not (disable_meta_dependencies | bool | default(false))
