---

- set_fact:
    homelab_storage_dir_name: loki
    loki_ramdisk_size: 1G
    loki_storage:
      boltdb_cache: '{{ tmpfs.mountpoint }}/loki/boltdb/cache'
      boltdb_index: '{{ tmpfs.mountpoint }}/loki/boltdb/index'
      compactor: '{{ tmpfs.mountpoint }}/loki/compactor'
      filesystem: '{{ tmpfs.mountpoint }}/loki/storage'
    zfs_dataset_name: zfs/loki
    zfs_mount_point: '{{ zfs.mountpoint }}/loki'

- include_tasks: '{{ playbook_dir }}/dry/github_release_downloader.yml'
  vars:
    repository_name: grafana/loki
    files_to_download:
      - logcli-linux-amd64.zip
      - loki-linux-amd64.zip
    files_to_install:
      logcli-linux-amd64: logcli
      loki-linux-amd64: loki
    install_on_boot: true

- name: Copy files to persistent storage
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/{{ item }}'
    force: true
  with_list:
    - rc.loki
    - loki.conf.yaml

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Start Loki
    script: |
      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/rc.loki' > /etc/rc.d/rc.loki
      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/loki.conf.yaml' > /etc/loki.conf.yaml
      chmod -v +x /etc/rc.d/rc.loki

      /etc/rc.d/rc.loki start

      (
        crontab -l 2>/dev/null
        echo
        echo "# Persistent Loki storage"
        echo "*/5 * * * * /etc/rc.d/rc.loki dump 2>&1 >/dev/null 2>&1
      ) | crontab -
