---
# https://github.com/riftbit/docker-serviio

# You will get a 15 day evaluation of the Pro edition, after which Serviio automatically reverts to the Free edition.
# -- https://serviio.org/download

- set_fact:  # noqa 502
    _name: dlna
    _volumes:
      - [ '/serviio', '/opt/serviio' ]
      - [ '/docker-entrypoint.sh', '/docker-entrypoint.sh', 'ro' ]

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: danie1k/serviio:latest
    include_secrets: false
    env:
      LOG_LEVEL: WARN
    webui: 'http://{{ _name }}.{{ lab_domain_name }}:23423/console/'
    networks:
      - name: '{{ docker_config.network.iot.name }}'
        ipv4_address: '{{ services.dlna.static_ip }}'
    volumes: '{{ _volumes|list + services.dlna.media_volumes|list }}'

    files:
      - src: docker-entrypoint.sh
        dest: ''
        force: true

    extra:
      cpus: 4
      memory: 5G
      kernel_memory: 7G

      # https://www.youtube.com/watch?v=S4fcR4s15OI
      mounts:
        - type: tmpfs
          target: /tmp
          tmpfs_size: 10737418240  # 10 GB
