[agent]
  # https://docs.influxdata.com/telegraf/latest/administration/configuration/#agent-configuration
  interval = "10s"
  logfile = ""
  quiet = true
  round_interval = true

[[outputs.influxdb]]
  # InfluxDB v1.x
  urls = [ "{{ influxdb_ingest_url }}" ]
  database = "telegraf"
  skip_database_creation = true


# https://grafana.com/grafana/dashboards/5357
# https://grafana.com/grafana/dashboards/7233

# APCUPSD - reads data from an apcupsd daemon over its NIS network protocol.
[[inputs.apcupsd]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/apcupsd/README.md
  servers = [ "tcp://127.0.0.1:3551" ]
  timeout = "5s"

# CPU - metrics on the system CPUs
[[inputs.cpu]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/cpu/README.md
  percpu = true
  totalcpu = true
  collect_cpu_time = true
  report_active = false
  fielddrop = ["time_*"]

# Disk - metrics about disk usage
[[inputs.disk]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/disk/README.md
  ignore_fs = [ "tmpfs", "devtmpfs", "devfs" ]

# DiskIO - metrics about disk traffic and timing
[[inputs.diskio]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/diskio/README.md
  # no custom settings

# Docker - metrics on running docker containers
[[inputs.docker]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/docker/README.md
  endpoint = "unix:///var/run/docker.sock"
  container_state_exclude = [ "removing" ]
  gather_services = false
  perdevice = true
  total = true

# Kernel - gathers info about the kernel that doesn't fit into other plugins.
[[inputs.kernel]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/kernel/README.md
  # no configuration avail

# Memory - collects system memory metrics
[[inputs.mem]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mem/README.md
  # no configuration avail

# Processes - gathers info about the total number of processes and groups them by status.
[[inputs.processes]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/processes/README.md
  # no configuration avail

# Net - metrics about network interface and protocol usage
[[inputs.net]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NET_README.md
  interfaces = [ "br[0-3]", "eth[0-3]" ]

# Netstat - collects TCP connections state and UDP socket counts by using lsof.
[[inputs.netstat]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/net/NETSTAT_README.md
  # no configuration avail

# LM Sensors - collects sensor metrics with the `sensors` executable from the lm-sensor package.
[[inputs.sensors]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/sensors/README.md
  # no custom settings

# S.M.A.R.T. - get metrics using the command line utility smartctl
[[inputs.smart]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/smart/README.md
  attributes = true
  nocheck = "standby"
  devices = [ "/dev/sdc", "/dev/sdd", "/dev/sde", "/dev/sdf", "/dev/sdg", "/dev/sdh", "/dev/sdi", "/dev/sdj" ]

# Swap - system swap metrics.
[[inputs.swap]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/swap/README.md
  # no configuration avail

# System - general stats on system load, uptime, and number of users logged in.
[[inputs.system]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/system/README.md
  # no configuration avail

# ZFS - metrics from ZFS filesystems.
[[inputs.zfs]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/zfs/README.md
  datasetMetrics = true
