# https://grafana.com/grafana/dashboards/9710

[agent]
# https://docs.influxdata.com/telegraf/latest/administration/configuration/#agent-configuration
interval = "1m"
logfile = ""
quiet = true
round_interval = true

[[outputs.influxdb]]
# InfluxDB v1.x
urls = [ "{{ services.influxdb.url }}" ]
database = "weather"
skip_database_creation = true

[[inputs.http]]
  # https://github.com/influxdata/telegraf/blob/master/plugins/inputs/http/README.md
  urls = [
    {% for city_id in services.telegraf.openweathermap.cities %}
    "https://api.openweathermap.org/data/2.5/weather?id={{ city_id }}&units=metric&appid={{ lab.services.telegraf.openweathermap.api_key }}",
    {% endfor %}
  ]
  method = "GET"

  data_format = "json"
  tag_keys = [ "coord_lon", "coord_lat", "sys_country", "id", "name" ]
  json_string_fields = [ "weather_0_main", "weather_0_description" ]
  json_time_key = "dt"
  json_time_format = "unix"
  name_override = "openweathermap"
