[http.middlewares]
  [http.middlewares.api-auth.basicAuth]
    users = [
      "{{ services.reverse_proxy.traefik_auth }}",
    ]

  # https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=overwriteprotocol#traefik-2
  [http.middlewares.nextcloud-redirectregex.redirectRegex]
    permanent = true
    regex = "https://(.*)/.well-known/(card|cal)dav"
    replacement = "https://${1}/remote.php/dav/"

# https://ssl-config.mozilla.org/#server=traefik&version=2.1.2&config=modern&hsts=false&guideline=5.6
[[tls.certificates]]
  certFile = "/tls/cert.pem"
  keyFile = "/tls/privkey.pem"

[tls.options]
[tls.options.modern]
  minVersion = "VersionTLS13"
