[api]
  dashboard = true

[log]
  level = "WARN"

[providers]
  [providers.docker]

  [providers.file]
    filename = "/config/dynamic.toml"
    watch = false

# https://doc.traefik.io/traefik/routing/entrypoints/
[entryPoints]
  # HTTP(S)
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.http.redirections]
      [entryPoints.http.http.redirections.entryPoint]
        to = "https"
        scheme = "https"

  [entryPoints.https]
    address = ":443"

    [entryPoints.https.http.tls]
      certResolver = "LETSENCRYPT"

      [[entryPoints.https.http.tls.domains]]
        main = "{{ lab_domain_name }}"
        sans = "*.{{ lab_domain_name }}"

   [entryPoints.service1]
     address = ":9091/tcp"
   [entryPoints.service2]
     address = ":9092/tcp"
   [entryPoints.service3]
     address = ":9093/tcp"
   [entryPoints.service4]
     address = ":9094/tcp"
   [entryPoints.service5]
     address = ":9095/tcp"

[certificatesResolvers.LETSENCRYPT.acme]
  storage = "config/letsencrypt.json"

  [certificatesResolvers.LETSENCRYPT.acme.dnsChallenge]
    provider = "cloudflare"
