---

- name: 'prometheus-config : Add "{{ job_name }}" job to Prometheus Config'
  ansible.builtin.blockinfile:
    insertafter: 'scrape_configs:'
    marker: '### {mark} {{ job_name | upper }}'
    marker_begin: '\/ START'
    marker_end: '/\ END'
    content: |2
        - job_name: '{{ job_name }}'
          {{ job | to_nice_yaml | indent(4) }}
    dest: '{{ unraid.services_data_dir }}/prometheus/config/prometheus.yml'
  register: _prometheus_config

- name: 'prometheus-config : Reload Prometheus'  # noqa 503
  uri:
    url: 'https://prometheus.{{ lab_domain_name }}/-/reload'
    method: POST
    status_code: 200
  when: _prometheus_config.changed
