---

# https://redis.io/topics/admin

- block:
    - name: Set kernel settings in boot script
      ansible.builtin.blockinfile:
        content: "{{ settings | join('\n') }}"
        dest: '{{ unraid.homelab_dir }}/boot.sh'
        marker: "# {mark} ANSIBLE_DOCKER_REDIS"
      register: _redis_kernel_settings_on_boot
    - name: Optimize kernel settings for Redis
      command: '{{ item }}'
      with_list: '{{ settings }}'
      when: _redis_kernel_settings_on_boot.changed
  vars:
    settings:
      - 'sysctl -w vm.overcommit_memory=1'
      - 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled'


- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: redis
    image: clearlinux/redis:latest
    command: redis-server /redis.conf
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '/data', '/data', 'rw' ]
      - [ '/redis.conf', '/redis.conf', 'ro' ]

    files:
      - src: redis.conf
        dest: ''
        force: true

    extra:
      cpus: 2
      memory: 12G
      kernel_memory: 14G
      sysctls:
        net.core.somaxconn: '1024'
