# https://github.com/AnalogJ/scrutiny/blob/master/example.scrutiny.yaml
version: 1

web:
  listen:
    port: {{ _port }}
    host: 0.0.0.0
    basepath: ''
  database:
    location: /opt/scrutiny/config/scrutiny.db
  src:
    frontend:
      path: /opt/scrutiny/web

  influxdb:
    host: 127.0.0.1
    port: 8086
    bucket: scrutiny
    retention_policy: true

log:
  file: ''
  level: {{ scrutiny_log_level }}

{% if services.scrutiny.notify.urls | list | length > 0 %}
notify:
  urls: {{ services.scrutiny.notify.urls }}
{% endif %}
