---

- set_fact:
    _rclone_config_remote_name: default_remote

- name: Removing existing rclone remote config
  community.general.ini_file:
    path: /boot/config/plugins/rclone/.rclone.conf
    section: '{{ _rclone_config_remote_name }}'
    state: absent

- name: Configure rclone remote
  community.general.ini_file:
    path: /boot/config/plugins/rclone/.rclone.conf
    section: '{{ _rclone_config_remote_name }}'
    option: '{{ item.key }}'
    value: '{% if item.value | type_debug == "bool" %}{{ item.value | string | lower }}{% else %}{{ item.value }}{% endif %}'
  with_dict: '{{ unraid_backups.rclone_remote }}'

- name: Copy filters file
  ansible.builtin.copy:
    content: '{{ lookup("template", role_path ~ "/_rclone/filters.txt") }}'
    dest: '{{ unraid.homelab_dir }}/unraid_backups/rclone-filters.txt'
    force: true

- name: Install User Script
  include_tasks: '{{ playbook_dir }}/dry/unraid/user-script.yml'
  vars:
    name: rclone_offsite_backups
    description: Offsite backups using rclone
    script: '{{ lookup("template", role_path ~ "/_rclone/user-script.sh") }}'
