---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: influxdb
    image: influxdb:1.8-alpine
    command: influxd -config /var/lib/influxdb/influxdb.conf
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/var/lib/influxdb', 'rw' ]

    files:
      - src: influxdb.conf
        dest: ''
