---

# docker exec -it influxdb influx -port 9090
# CREATE DATABASE <db_name>;
# CREATE RETENTION POLICY <name> ON <db_name> DURATION ___ REPLICATION 1 DEFAULT;

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: 'influxdb'
    image: influxdb:1.8-alpine
    command: influxd -config /var/lib/influxdb/influxdb.conf
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/var/lib/influxdb', 'rw' ]

    proxy:
      - tcp_entrypoint: tcp0 # docker_container_reverseproxy/files/traefik/traefik.toml
        tcp_port: 9090

    files:
      - src: influxdb.conf
        dest: ''
