---

# https://github.com/bastienwirtz/homer

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: home
    image: b4bz/homer:latest
    env:
      UID: '0'
      GID: '0'
      PORT: '80'
    log_driver: local
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/www/assets', 'rw' ]

    proxy:
      - http_port: 80
