---

- name: Create permanent storage directory
  ansible.builtin.file:
    path: '{{ secrets.storage.permanent }}'
    state: directory

- name: Copy entrypoint script
  ansible.builtin.template:
    src: entrypoint.sh
    dest: '{{ secrets.storage.permanent }}/entrypoint.sh'
    force: true

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install secrets
    script: |2
      mkdir -vp '{{ secrets.storage.on_host }}'
      mount -v -t tmpfs -o size=10M,noatime tmpfs '{{ secrets.storage.on_host }}'
      cp -rvf '{{ secrets.storage.permanent }}'/* '{{ secrets.storage.on_host }}'/
      chmod -v 555 '{{ secrets.storage.on_host }}'/*
