---

- assert:  # noqa 502
    that: ['name is defined', 'name | length > 0']
    fail_msg: "Missing or empty 'name'"
- assert:  # noqa 502
    that: ['script is defined', 'script | length > 0']
    fail_msg: "Missing or empty 'script'"

- set_fact:  # noqa 502
    _execute_immediately: '{{ execute_immediately | default(true) | bool }}'
    _slugified_name: '{{ name | lower | replace(" ", "_") }}'

- ansible.builtin.shell: 'date +%Y-%m-%dT%H-%M-%S'  # noqa 502 305
  register: tstamp
  changed_when: false

- set_fact:  # noqa 502
#    _boot_backup_file: '{{ _boot_script_path }}.{{ tstamp.get("stdout", "date") }}.{{ _slugified_name }}.bak'
    _boot_script_file: '{{ unraid.scripts_dir }}/boot_{{ _slugified_name }}.sh'

- ansible.builtin.copy:
    content: |
      #!/bin/sh
      logger 'Booting: {{ name }}'

      {{ script }}
    dest: '{{ _boot_script_file }}'
    force: true
