---

- set_fact:
    program: |
      [program:{{ name }}-{{ item.key }}]
      autorestart = {{ (item.value.autorestart | default(false)) | string | lower }}
      autostart = {{ (item.value.autostart | default(false)) | string | lower }}
      command = {{ item.value.command }}
      killasgroup = {{ (item.value.killasgroup | default(false)) | string | lower }}
      priority = {{ item.value.priority | default(1) }}
      process_name = %(program_name)s
      stderr_logfile = /var/log/%(program_name)s.log
      stderr_logfile_backups = 0
      stdout_logfile = /var/log/%(program_name)s.log
      stdout_logfile_backups = 0
      stopasgroup = {{ (item.value.stopasgroup | default(false)) | string | lower }}
  with_dict: '{{ programs }}'
  register: _programs

- set_fact:
    config_programs: "{{ _programs.results | map(attribute='ansible_facts') | map(attribute='program') | join('\n') }}"
    config_group: ''

- set_fact:
    config_group: |
      [group:{{ name }}]
      programs = {{ [name ~ '-'] | product(programs.keys()) | map('join') | join(',') }}
  when: 'programs.keys() | length > 1'

- name: Create Supervisord config file
  ansible.builtin.copy:
    content: "{{ config_programs }}\n\n{{ config_group }}"
    dest: '{{ unraid.homelab_dir }}/supervisord/supervisor.d/{{ name }}.conf'  # `prerequisites/unraid`
    force: true
