---

# This task requires "CA User Scripts" application to be installed via "Community Applications" plugin

- assert:  # noqa 502
    that: ['name is defined', 'name | length > 0']
    fail_msg: "Missing or empty 'name'"
- assert:  # noqa 502
    that: ['description is defined', 'description | length > 0']
    fail_msg: "Missing or empty 'description'"
- assert:  # noqa 502
    that: ['script is defined', 'script | length > 0']
    fail_msg: "Missing or empty 'script'"

- name: 'user-script : {{ name }} : Create script directory'
  ansible.builtin.file:
    path: '/boot/config/plugins/user.scripts/scripts/{{ name }}'
    state: directory

- name: 'user-script : {{ name }} : Script description'
  ansible.builtin.copy:
    content: '{{ description | default("") }}'
    dest: '/boot/config/plugins/user.scripts/scripts/{{ name }}/description'
    force: true

- name: 'user-script : {{ name }} : Script code'
  ansible.builtin.copy:
    content: '{{ script }}'
    dest: '/boot/config/plugins/user.scripts/scripts/{{ name }}/script'
    force: true
