# https://github.com/influxdata/influxdata-docker/blob/master/influxdb/1.8/influxdb.conf
# https://docs.influxdata.com/influxdb/v1.8/administration/config/

# InfluxData uses voluntarily reported data from running InfluxDB nodes
# primarily to track the adoption rates of different InfluxDB versions.
# This data helps InfluxData support the continuing development of InfluxDB.
reporting-disabled = false

# The bind address to use for the RPC service for backup and restore.
bind-address = "{{ _influx_config.bind_address.rpc }}"

[meta]
# This section controls parameters for the InfluxDB metastore, which stores
# information on users, databases, retention policies, shards,
# and continuous queries.

  # The directory where the metadata/raft database is stored.
  # Files in themeta directory include meta.db, the InfluxDB metastore file.
  dir = "{{ _influx_config.dir.meta }}"

  # Enables the automatic creation of the DEFAULT retention policy autogen
  # when a database is created.
  # retention-autocreate = true

  # Enables the logging of messages from the meta service.
  # logging-enabled = true


# =============================================================================
# Data settings
# =============================================================================

# This section controls where the actual shard data for InfluxDB lives
# and how it is flushed from the Write-Ahead Log (WAL).
[data]
  # series-file-max-concurrent-snapshot-compactions = 0
  # strict-error-handling = false

  # The InfluxDB directory where the TSM engine stores TSM files.
  dir = "{{ _influx_config.dir.data }}"

  # The location of the directory for write ahead log (WAL) files.
  wal-dir = "{{ _influx_config.dir.wal }}"

  # The amount of time that a write waits before fsyncing. Use a duration
  # greater than 0 to batch up multiple fsync calls. This is useful for slower
  # disks or when experiencing WAL write contention.
  # The default value of "0s" fsyncs every write to the WAL.
  wal-fsync-delay = "100ms"
  # For non-SSD disks, InfluxData recommends values in the range of 0ms-100ms.

  # The type of shard index to use for new shards.
  # - "inmem" (default) --  an in-memory index that is recreated at startup.
  # - "tsi1" - the Time Series Index (TSI) disk-based index.
  # index-version = "inmem"

  # Enables verbose logging of additional debug information within the TSM
  # engine and WAL. The trace logging provide more useful output for debugging
  # TSM engine issues.
  trace-logging-enabled = false

  # Enables the logging of parsed queries before execution. The query log
  # can be useful for troubleshooting, but logs any sensitive data contained
  # within a query.
  query-log-enabled = false

  # Validates incoming writes to ensure measurement keys and tag keys only have
  # valid Unicode characters. This setting will incur a small overhead because
  # every key must be checked. This will not validate field keys.
  validate-keys = false

  # Settings for the TSM engine
  # ---------------------------------------------------------------------------

  # The maximum size that a shard cache can reach before it starts rejecting
  # writes.
  cache-max-memory-size = "{{ _influx_config.ramdisk_size }}"

  # The size at which the engine will snapshot the cache and write it
  # to a TSM file, freeing up memory.
  cache-snapshot-memory-size = "1M"

  # The time interval at which the engine will snapshot the cache and write it
  # to a new TSM file if the shard hasn’t received writes or deletes.
  cache-snapshot-write-cold-duration = "5m0s"

  # The time interval at which the TSM engine will compact all TSM files
  # in a shard if it hasn’t received a write or delete.
  compact-full-write-cold-duration = "2h0m0s"

  # The maximum number of concurrent full and level compactions that can run
  # at one time. The default value of 0 results in 50% of the CPU cores being
  # used at runtime for compactions. If explicitly set, the number of cores
  # used for compaction is limited to the specified value.
  max-concurrent-compactions = {{ _influx_config.cpu_cores }}

  # The maximum number of bytes per seconds TSM compactions write to disk.
  # Default is "48m" (48 million). Note that short bursts are allowed to happen
  # at a possibly larger value, set by compact-throughput-burst.
  # compact-throughput = "48m"

  # The maximum number of bytes per seconds TSM compactions write to disk
  # during brief bursts. Default is "48m" (48 million).
  # compact-throughput-burst = "48m"

  # If true, then the MMap Advise value MADV_WILLNEED advises the kernel about
  # how to handle the mapped memory region in terms of input/output paging
  # and to expect access to the mapped memory region in the near future, with
  # respect to TSM files.
  # Because this setting has been problematic on some kernels (including CentOS
  # and RHEL), the default is false.
  # Changing value to true might help users who have slow disks in some cases.
  tsm-use-madv-willneed = true

  # In-memory (inmem) index settings
  # ---------------------------------------------------------------------------

  # The maximum number of series allowed per database before writes are
  # dropped. The default setting is 1000000 (one million). Change the setting
  # to 0 to allow an unlimited number of series per database.
  # max-series-per-database = 1000000

  # The maximum number of tag values allowed per tag key. The default value
  # is 100000 (one hundred thousand). Change the setting to 0 to allow
  # an unlimited number of tag values per tag key. If a tag value causes
  # the number of tag values of a tag key to exceed max-values-per-tag, then
  # InfluxDB will not write the point, and it returns a partial write error.
  # max-values-per-tag = 100000

  # TSI (tsi1) index settings
  # ---------------------------------------------------------------------------

  # The threshold, in bytes, when an index write-ahead log (WAL) file will
  # compact into an index file.
  # Lower sizes will cause log files to be compacted more quickly and result in
  # lower heap usage at the expense of write throughput.
  # Higher sizes will be compacted less frequently, store more series
  # in-memory, and provide higher write throughput.
  # max-index-log-file-size = "1M"

  # The size of the internal cache used in the TSI index to store previously
  # calculated series results. Cached results will be returned quickly from the
  # cache rather than needing to be recalculated...
  # series-id-set-cache-size = 100


# =============================================================================
# Query management settings
# =============================================================================

# This section contains configuration settings for query management
# https://docs.influxdata.com/influxdb/v1.8/troubleshooting/query_management/
[coordinator]
  # The duration a write request waits until a “timeout” error is returned
  # to the caller. The default value is 10 seconds.
  # write-timeout = "10s"

  # The maximum number of running queries allowed on your instance.
  # The default setting (0) allows for an unlimited number of queries.
  # max-concurrent-queries = 0

  # The maximum duration that a query is allowed to execute before InfluxDB
  # kills the query. The default setting (0) allows queries to run with no time
  # restrictions. This setting is a duration.
  # query-timeout = "0s"

  # The maximum duration that a query can until InfluxDB logs the query with
  # a Detected slow query message. The default setting ("0") will never tell
  # InfluxDB to log the query. This setting is a duration.
  # log-queries-after = "0s"

  # The maximum number of points that a SELECT statement can process.
  # The default setting (0) allows the SELECT statement to process
  # an unlimited number of points.
  # max-select-point = 0

  # The maximum number of series that a SELECT statement can process.
  # The default setting (0) allows the SELECT statement to process
  # an unlimited number of series.
  # max-select-series = 0

  # The maximum number of GROUP BY time() buckets that a query can process.
  # The default setting (0) allows a query to process an unlimited
  # number of buckets.
  # max-select-buckets = 0


# =============================================================================
# Retention policy settings
# =============================================================================

# This section controls the enforcement of retention policies for evicting
# old data.
[retention]
  # Set to false to prevent InfluxDB from enforcing retention policies.
  enabled = true

  # The time interval at which InfluxDB checks to enforce a retention policy.
  # check-interval = "30m0s"


# =============================================================================
# Shard precreation settings
# =============================================================================

# This section controls the precreation of shards so that shards are available
# before data arrive. Only shards that, after creation, will have both a start-
# and end-time in the future are ever created. Shards that would be wholly
# or partially in the past are never precreated.
[shard-precreation]
  # Determines whether the shard precreation service is enabled.
  enabled = true

  # The time interval when the check to precreate new shards runs.
  # check-interval = "10m0s"

  # The maximum period in the future for which InfluxDB precreates shards.
  # The 30m default should work for most systems. Increasing this setting too
  # far in the future can cause inefficiencies.
  # advance-period = "30m0s"


# =============================================================================
# Monitoring settings
# =============================================================================

# This section controls the InfluxDB system self-monitoring.
# https://github.com/influxdata/influxdb/blob/1.8/monitor/README.md
#
# By default, InfluxDB writes the data to the _internal database. If that
# database does not exist, InfluxDB creates it automatically.
# The DEFAULT retention policy on the _internal database is seven days.
# If you want to use a retention policy other than the seven-day retention
# policy, you must create it.
[monitor]
  # Set to false to disable recording statistics internally. If set to false it
  # will make it substantially more difficult to diagnose issues
  # with your installation.
  store-enabled = true

  # The destination database for recorded statistics.
  # store-database = "_internal"

  # The time interval at which InfluxDB records statistics.
  # The default value is every ten seconds (10s).
  # store-interval = "10s"


# =============================================================================
# HTTP endpoints settings
# =============================================================================

# This section controls how InfluxDB configures the HTTP endpoints.
# These are the primary mechanisms for getting data into and out of InfluxDB.
[http]
  # flux-log-enabled = false
  # prom-read-auth-enabled = false

  # Determines whether the HTTP endpoints are enabled.
  # Note that the InfluxDB command line interface (CLI) connects to the
  # database using the InfluxDB API.
  enabled = true

  # Determines whether the Flux query endpoint is enabled.
  flux-enabled = false

  # The bind address (port) used by the HTTP service.
  bind-address = "{{ _influx_config.bind_address.http }}"

  # Determines whether user authentication is enabled over HTTP and HTTPS.
  # To require authentication, set the value to true.
  auth-enabled = false

  # The default realm sent back when issuing a basic authentication challenge.
  # The realm is the JWT realm used by the HTTP endpoints.
  # realm = "InfluxDB"

  # Determines whether HTTP request logging is enabled.
  log-enabled = false

  # Determines whether the HTTP write request logs should be suppressed
  # when the log is enabled.
  suppress-write-log = true

  # The path to the access log, which determines whether detailed write logging
  # is enabled using log-enabled = true.
  # access-log-path = ""

  # Filters which requests should be logged...
  # access-log-status-filters = []

  # Determines whether detailed write logging is enabled. Set to true to enable
  # logging for the write payload. If set to true, this will duplicate every
  # write statement in the logs and is thus not recommended for general use.
  write-tracing = false

  # Determines whether the /net/http/pprof HTTP endpoint is enabled.
  # Useful for troubleshooting and monitoring.
  pprof-enabled = true

  # Enables authentication on /debug endpoints. If enabled, users need admin
  # permissions to access the following endpoints:
  # /debug/pprof, /debug/requests, /debug/vars
  pprof-auth-enabled = false

  # Enable the default /pprof endpoint and bind against localhost:6060.
  # Useful for debugging startup performance issues.
  debug-pprof-enabled = false

  # Enables authentication on the /ping, /metrics, and deprecated /status
  # endpoints. This setting has no effect if auth-enabled is set to false.
  ping-auth-enabled = false

  # Determines whether HTTPS is enabled.
  https-enabled = true

  # The path of the SSL certificate file to use when HTTPS is enabled.
  https-certificate = "{{ unraid.tls_storage_dir }}/cert.pem"

  # Use a separate private key location.
  # If only the https-certificate is specified, the httpd service will try
  # to load the private key from the https-certificate file.
  # If a separate https-private-key file is specified, the httpd service will
  # load the private key from the https-private-key file.
   https-private-key = "{{ unraid.tls_storage_dir }}/privkey.pem"

  # The shared secret used to validate public API requests using JWT tokens.
  # shared-secret = ""

  # The maximum number of rows that the system can return in a non-chunked
  # query. The default setting (0) allows for an unlimited number of rows.
  max-row-limit = 0

  # The maximum number of connections that may be open at once.
  max-connection-limit = 0

  # Enable HTTP service over the UNIX domain socket.
  unix-socket-enabled = false

  # The path of the UNIX domain socket.
  # bind-socket = "/var/run/influxdb.sock"

  # unix-socket-permissions = "0777"

  # The maximum size, in bytes, of a client request body.
  # max-body-size = 25000000

  # The maximum number of writes that can be processed concurrently.
  max-concurrent-write-limit = 0

  # The maximum number of writes queued for processing.
  max-enqueued-write-limit = 0

  # The maximum duration for a write to wait in the queue to be processe.
  # enqueued-write-timeout = 30000000000

  # User-supplied HTTP response headers. Configure this section
  # to return security headers such as X-Frame-Options
  # or Content Security Policy where needed.
  # [http.headers]


# =============================================================================
# Logging settings
# =============================================================================

# Controls how the logger emits logs to the output.
[logging]
  # Determines which log encoder to use for logs. Values: auto, logfmt, json.
  format = "auto"

  # The log level to be emitted. Values: error, warn, info, debug.
  level = "{{ _influx_config.logging_level }}"

  # Suppresses the logo output that is printed when the program is started.
  suppress-logo = true


# =============================================================================
# Subscription settings
# =============================================================================

# This section controls how Kapacitor will receive data.
# https://docs.influxdata.com/kapacitor/
[subscriber]
  # Determines whether the subscriber service is enabled.
  enabled = true

  # The duration that an HTTP write to a subscriber runs until it times out.
  # http-timeout = "30s"

  # Determines whether to allow insecure HTTPS connections to subscribers.
  # This is useful when testing with self-signed certificates.
  insecure-skip-verify = false

  # The path to the PEM-encoded CA certs file. If the value is an empty
  # string (""), the default system certs will be used.
  # ca-certs = "/tls/cert.pem"

  # The number of writer goroutines processing the write channel.
  # write-concurrency = 40

  # The number of in-flight writes buffered in the write channel.
  # write-buffer-size = 1000


# =============================================================================
# Continuous queries settings
# =============================================================================

# This settings control how continuous queries (CQs) run within InfluxDB.
# Continuous queries are automated batches of queries that execute over recent
# time intervals.
# https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#continuous-query-cq
[continuous_queries]
  enabled = true
  log-enabled = false

  # When set to true, continuous query execution statistics are written
  # to the default monitor store.
  query-stats-enabled = false

  # The interval at which InfluxDB checks to see if a CQ needs to run.
  # Set this option to the lowest interval at which your CQs run. For example,
  # if your most frequent CQ runs every minute, set run-interval to 1m.
  run-interval = "1m"


# =============================================================================
# Transport Layer Security (TLS) settings
# =============================================================================

# Global configuration settings for Transport Layer Security (TLS) in InfluxDB.
# https://docs.influxdata.com/influxdb/v1.8/administration/https_setup/
#[tls]
#  ciphers = []
#  min-version = ""
#  max-version = ""


# =============================================================================
# Graphite settings
# =============================================================================

# https://docs.influxdata.com/influxdb/v1.8/supported_protocols/graphite/
[[graphite]]
  enabled = false
  # bind-address = ":2003"
  # database = "graphite"
  # retention-policy = ""
  # protocol = "tcp"
  # batch-size = 5000
  # batch-pending = 10
  # batch-timeout = "1s"
  # consistency-level = "one"
  # separator = "."
  # udp-read-buffer = 0


# =============================================================================
# CollectD settings
# =============================================================================

# https://docs.influxdata.com/influxdb/v1.8/supported_protocols/collectd/
[[collectd]]
  enabled = false
  # bind-address = ":25826"
  # database = "collectd"
  # retention-policy = ""
  # batch-size = 5000
  # batch-pending = 10
  # batch-timeout = "10s"
  # read-buffer = 0
  # typesdb = "/usr/share/collectd/types.db"
  # security-level = "none"
  # auth-file = "/etc/collectd/auth_file"
  # parse-multivalue-plugin = "split"


# =============================================================================
# OpenTSDB settings
# =============================================================================

# https://docs.influxdata.com/influxdb/v1.8/supported_protocols/opentsdb/
[[opentsdb]]
  enabled = false
  # bind-address = ":4242"
  # database = "opentsdb"
  # retention-policy = ""
  # consistency-level = "one"
  # tls-enabled = false
  # certificate = "/etc/ssl/influxdb.pem"
  # batch-size = 1000
  # batch-pending = 5
  # batch-timeout = "1s"
  # log-point-errors = true


# =============================================================================
# UDP settings
# =============================================================================

# https://docs.influxdata.com/influxdb/v1.8/supported_protocols/udp/
[[udp]]
  enabled = false
  # bind-address = ":8089"
  # database = "udp"
  # retention-policy = ""
  # batch-size = 5000
  # batch-pending = 10
  # read-buffer = 0
  # batch-timeout = "1s"
  # precision = ""
