---

# Remember to manually create InfluxDB database first!
# >>> CREATE DATABASE telegraf;
# >>> CREATE RETENTION POLICY one_month ON telegraf DURATION 4w REPLICATION 1 DEFAULT;

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: telegraf
    image: telegraf:1.17-alpine
    command: tail -f /dev/null
    env:
      HOST_MOUNT_PREFIX: /hostfs # [[inputs.disk]]
      HOST_PROC: /hostfs/proc # [[inputs.disk]], [[inputs.processes]]
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '/telegraf.conf', '/etc/telegraf/telegraf.conf', 'rw' ]
      - '/:/hostfs:ro' # [[inputs.disk]], [[inputs.processes]], [[inputs.zfs]]
      - '/var/run/docker.sock:/var/run/docker.sock:ro' # [[inputs.docker]]

    templates:
      - src: telegraf.conf
        dest: ''
