---

- set_fact:
    _directory: '{{ unraid.homelab_dir }}/docker_improvements'
    icons:
      docker.png: question.png
      docker-image.png: image.png

- name: 'docker_improvements : Create directory for persistent files'
  ansible.builtin.file:
    path: '{{ _directory }}'
    state: directory

- name: 'docker_improvements : Copy files to persistent storage'
  ansible.builtin.copy:
    src: '{{ role_path }}/_docker_improvements/{{ item }}'
    dest: '{{ _directory }}/{{ item }}'
    force: true
  with_list:
    - css.css
    - docker.png
    - docker-image.png
    - docker-webui-url.patch
    - reattach-docker-networks.patch

- name: 'docker_improvements : Copy icons to persistent storage'
  ansible.builtin.copy:
    src: '{{ _directory }}/{{ item.key }}'
    remote_src: true
    dest: '/usr/local/emhttp/plugins/dynamix.docker.manager/images/{{ item.value }}'
    force: true
  with_dict: '{{ icons }}'

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install Docker Improvements
    script: |2
      # Icons
      {% for key, value in icons.items() %}
      cp -vf '{{ _directory }}/{{ key }}' '/usr/local/emhttp/plugins/dynamix.docker.manager/images/{{ value }}'
      {% endfor %}

      sed -i 's#/webGui/images/disk.png#/plugins/dynamix.docker.manager/images/image.png#g' \
        /usr/local/emhttp/plugins/dynamix.docker.manager/include/DockerContainers.php

      # Reattach Docker Networks
      fromdos < '{{ _directory }}/reattach-docker-networks.patch' > '{{ unraid.boot_tmp_dir }}'/reattach-docker-networks.patch
      patch --verbose /usr/local/etc/rc.d/rc.docker '{{ unraid.boot_tmp_dir }}'/reattach-docker-networks.patch

      # WebUI URL
      fromdos < '{{ _directory }}/docker-webui-url.patch' > '{{ unraid.boot_tmp_dir }}'/docker-webui-url.patch
      patch --verbose /usr/local/emhttp/plugins/dynamix.docker.manager/include/DockerClient.php '{{ unraid.boot_tmp_dir }}'/docker-webui-url.patch

      # WebUI CSS
      fromdos < '{{ _directory }}/css.css' >> /usr/local/emhttp/webGui/styles/default-white.css
