---

# https://github.com/linuxserver/docker-wikijs

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: wiki
    image: linuxserver/wikijs:latest
    env:
      # https://docs.linuxserver.io/images/docker-wikijs
      PUID: '99' # UID of 'nobody'
      PGID: '100' # GID of 'nobody'
      TZ: Europe/Warsaw
      UMASK: '000'
    networks:
      - name: '{{ docker.internal_network_name }}'
      - name: '{{ docker.external_network_name }}' # Because Wiki.js needs access the Internet sometimes
    volumes:
      - [ '/wikijs/config', '/config', 'rw' ]
      - [ '/wikijs/data', '/data', 'rw' ]

    templates:
      - src: wikijs/config.yml
        dest: 'wikijs/config/'

    proxy:
      - http_port: 3000

    extra:
      cpus: 2
      memory: 2G
      kernel_memory: 3G
