---

- name: Create persistent storage directory on the Flash drive
  ansible.builtin.file:
    path: '{{ unraid.homelab_dir }}/loki_promtail'
    state: directory

- name: Get latest release version number
  ansible.builtin.shell: 'curl -s https://api.github.com/repos/grafana/loki/releases/latest | jq -r .tag_name'
  register: _latest_loki_release
  changed_when: false

- name: Download & unzip latest binaries to persistent storage
  ansible.builtin.unarchive:
    src: '{{ item.value }}'
    remote_src: yes
    dest:  '{{ unraid.homelab_dir }}/loki_promtail/'
    creates: '{{ unraid.homelab_dir }}/loki_promtail/{{ item.key }}'
  with_dict: '{{ _downloads }}'
  vars:
    _install_version: '{{ _latest_loki_release.stdout }}'

- name: Copy Supervisord config to persistent storage
  ansible.builtin.copy:
    src: supervisord.conf
    dest: '{{ unraid.homelab_dir }}/supervisord/supervisor.d/loki_promtail.conf'
    force: true

- name: Copy Syslog config to persistent storage
  ansible.builtin.copy:
    src: syslog.conf
    dest: '{{ unraid.homelab_dir }}/loki_promtail/syslog.conf'
    force: true

- name: Copy Loki & Promtail config to persistent storage
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/loki_promtail/{{ item }}'
    force: true
  with_list:
    - loki.conf.yaml
    - promtail.conf.yaml

- name: Set up boot script
  ansible.builtin.blockinfile:
    content: '{{ lookup("template", role_path ~ "/other/boot.sh") }}'
    dest: '{{ unraid.homelab_dir }}/boot.sh'
    marker: "# {mark} ANSIBLE_LOKI_PROMTAIL"

- name: Install User Script
  include_tasks: '{{ playbook_dir }}/dry/unraid/user-script.yml'
  vars:
    name: loki_promtail_update
    description: Update Logcli, Loki & Promtail
    script: '{{ lookup("template", role_path ~ "/other/update.sh") }}'
