---

- set_fact:
    _dbpath: /data/db
    _name: mongodb
    _ram_limit: 6  # GB

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: mongo:latest
    icon: '{{ _name }}'

    command: [
      # https://www.mongodb.com/docs/manual/reference/program/mongod/
      'mongod',
      '--bind_ip_all',
      '--dbpath', '{{ _dbpath }}',
      '--directoryperdb',
      '--enableFreeMonitoring', 'off',
      '--nojournal',
      '--nounixsocket',
      '--profile', '0',
      '--tlsMode', 'disabled',
      '--wiredTigerCacheSizeGB', '{{ _ram_limit | string }}',
    ]

    env:
      MONGO_INITDB_ROOT_USERNAME_FILE: /opt/secrets/MONGODB_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD_FILE: /opt/secrets/MONGODB_INITDB_ROOT_PASSWORD

    include_secrets: false
    log_driver: local

    networks:
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.mongodb.static_ip }}'
      - name: '{{ docker_config.network.internal.name }}'
    volumes:
      - [ '/configdb', '/data/configdb', 'rw' ]
      - [ '/data',     '{{ _dbpath }}',  'rw' ]
      - '{{ secrets.docker.volume }}'

    extra:
      user: '{{ docker_config.default_user }}'
      cpus: 4
      memory: '{{ _ram_limit }}G'
      kernel_memory: '{{ _ram_limit * 1.5 }}G'

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: mongo-express
    image: mongo-express
    icon: '{{ _name }}'
    include_secrets: true
    log_driver: local

    env:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: !!str 'true'

    networks:
      - name: '{{ docker_config.network.internal.name }}'

    proxy:
      - http_port: 8081
