---

- name: Create directory for persistent files
  ansible.builtin.file:
    path: '{{ unraid.homelab_dir }}/unraid_backups'
    state: directory

- include_tasks: '{{ role_path }}/_rclone/task.yml'
- include_tasks: '{{ role_path }}/_rsync/task.yml'
- include_tasks: '{{ role_path }}/_zfs_sanoid/task.yml'
