---

- set_fact:  # noqa 502
    _name: anime-catalog

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: 'docker.{{ lab_domain_name }}/{{ _name }}:latest'
    icon: anime
    include_secrets: false
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}' # for 'pip install' etc.
    volumes:
      - '{{ zfs.mountpoint }}/encrypted/~git/anime-catalog/src:/app:ro'

    proxy:
      - http_port: 4321
