---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres
    image: clearlinux/postgres:11 # https://hub.docker.com/r/clearlinux/postgres
    env:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/var/lib/postgresql/data', 'rw' ]
