---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres
    image: clearlinux/postgres:11 # https://hub.docker.com/r/clearlinux/postgres
    command: >-
      postgres
      -c log_connections=off
      -c log_destination=stderr
      -c log_disconnections=off
      -c log_statement=none
      -c logging_collector=off
    env:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      PGDATA: /var/lib/pgsql/data
    networks:
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/var/lib/pgsql/data', 'rw' ]
