---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres
    image: clearlinux/postgres:11 # https://hub.docker.com/r/clearlinux/postgres
    env:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
    labels:
      haproxy.source_port: '5432'
      haproxy.target_port: '5432'
    networks:
      - name: '{{ docker.external_network_name }}'
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/var/lib/postgresql/data', 'rw' ]
