---

- assert:  # noqa 502
    that: ['parent_container_name is defined', 'parent_container_name | length > 0']
    fail_msg: "Missing or empty 'parent_container_name'"

- assert:  # noqa 502
    that: ['"redis" not in parent_container_name|lower']
    fail_msg: "Word 'redis' is forbidden in 'parent_container_name' variable"

- ansible.builtin.pause:  # noqa 502
    prompt: "Enter REDIS password to set, or press [Enter] to continue without password"
    echo: no
  register: _raw_redis_password

- set_fact:  # noqa 502
    redis_cpus: '{{ cpus | default("2") }}'
    redis_maxconn: '{{ maxconn | default("1024") }}'
    redis_password: '{{ _raw_redis_password.user_input.strip() }}'
    redis_port: '{{ 7000 | random(start=5000) }}'

- include_tasks: ./unraid-container.yml
  vars:
    name: 'redis-{{ parent_container_name }}'
    image: '{{ redis_image | default("redis:alpine") }}'
    include_secrets: false
    command: /redis/redis.conf
    icon: redis
    webui: false
    service_data_dir: '{{ parent_container_name }}/redis'
    volumes:
      - [ '', '/redis' ]

    templates:
      - src: '{{ playbook_dir }}/dry/docker/files/redis.conf'
        dest: ''
        force: true

    extra:
      cpus: '{{ redis_cpus }}'
      memory: 8G
      kernel_memory: 8G
      user: '{{ docker_config.default_user }}'
      sysctls:
        net.core.somaxconn: '{{ redis_maxconn }}'

- set_fact:
    redis_host: 'redis-{{ parent_container_name }}.{{ docker_config.network.internal.name }}'
