---

- assert:
    that: [volume_location != '']
    fail_msg: "Missing 'volume_location'"

- set_fact:
    _name_prefix: "Dry : Docker : Unraid Volume : [{{ volume_name }}]"

- name: '{{ _name_prefix }} Persistent directory on unRAID share'
  file:
    path: '{{ volume_location }}/{{ volume_name }}'
    state: directory
    owner: nobody
    group: users
    mode: ugo=rwx

- name: '{{ _name_prefix }} Symlink upcoming Docker Volume dir to persistent directory'
  file:
    src: '{{ volume_location }}/{{ volume_name }}'
    path: "/var/lib/docker/volumes/{{ volume_name | regex_replace('[^a-zA-Z0-9_.-]+', '-') }}"
    state: link

- name: '{{ _name_prefix }} Create actual Docker Volume'
  # https://docs.ansible.com/ansible/latest/collections/community/general/docker_volume_module.html
  community.general.docker_volume:
    volume_name: "{{ volume_name | regex_replace('[^a-zA-Z0-9_.-]+', '-') }}"
    driver: local
    labels:
      ManagedBy: Ansible
    recreate: never
    state: present
