---
# CREATE DATABASE yourdbname;
# CREATE USER youruser WITH ENCRYPTED PASSWORD 'yourpass';
# GRANT ALL PRIVILEGES ON DATABASE yourdbname TO youruser;

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres
    image: clearlinux/postgres:11  # https://hub.docker.com/r/clearlinux/postgres
    command: >-
      postgres
      -c log_connections=off
      -c log_destination=stderr
      -c log_disconnections=off
      -c log_statement=none
      -c logging_collector=off
    env:
      POSTGRES_USER: '{{ services.postgresql.root_username }}'
      POSTGRES_PASSWORD: '{{ services.postgresql.root_password }}'
      PGDATA: /var/lib/pgsql/data
    networks:
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.postgresql.static_ip }}'
      - name: '{{ docker_config.network.internal.name }}'
        aliases: [ '{{ services.postgresql.ingest_host }} }' ]
    volumes:
      - [ '', '/var/lib/pgsql/data', 'rw' ]

    extra:
      cpus: 4
      memory: 6G
      kernel_memory: 8G
