---
# CREATE USER youruser WITH ENCRYPTED PASSWORD 'yourpass';
# CREATE DATABASE yourdbname OWNER youruser;
# GRANT ALL PRIVILEGES ON DATABASE yourdbname TO youruser;

# unraid/secrets:
#  POSTGRES_USER      -  root username
#  POSTGRES_PASSWORD  -  root password

- set_fact:
    _pgdata: /var/lib/pgsql/data

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres
    image: postgres:11-alpine
    icon: postgresql
    include_secrets: true
    command: >-
      postgres
      -c log_connections=off
      -c log_destination=stderr
      -c log_disconnections=off
      -c log_statement=none
      -c logging_collector=off
    env:
      PGDATA: '{{ _pgdata }}'
    networks:
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.postgresql.static_ip }}'
      - name: '{{ docker_config.network.internal.name }}'
        aliases: [ '{{ services.postgresql.ingest_host }} }' ]
    volumes:
      - [ '', '{{ _pgdata }}', 'rw' ]

    extra:
      cpus: 4
      memory: 6G
      kernel_memory: 8G

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: postgres14
    image: postgres:14-alpine
    icon: postgresql
    include_secrets: true
    command: >-
      postgres
      -c log_connections=off
      -c log_destination=stderr
      -c log_disconnections=off
      -c log_statement=none
      -c logging_collector=off
    env:
      PGDATA: '{{ _pgdata }}'
    networks:
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.postgresql14.static_ip }}'
      - name: '{{ docker_config.network.internal.name }}'
        aliases: [ '{{ services.postgresql14.ingest_host }} }' ]
    volumes:
      - [ '', '{{ _pgdata }}', 'rw' ]

    extra:
      cpus: 4
      memory: 6G
      kernel_memory: 8G
