---
# https://docs.linuxserver.io/images/docker-scrutiny

- set_fact:  # noqa 502
    _device: '{{ item }}:{{ item }}'
  with_list: '{{ services.scrutiny.drives }}'
  register: _devices

- set_fact:  # noqa 502
    _devices: '{{ _devices.results | map(attribute="ansible_facts._device") | list | sort }}'
    _port: '8080'

- debug:
    var: _devices

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: scrutiny
    image: ghcr.io/linuxserver/scrutiny:latest
    env:
      GIN_MODE: release  # https://stackoverflow.com/a/48926122
      SCRUTINY_API_ENDPOINT: 'http://127.0.0.1:{{ _port }}'
      SCRUTINY_COLLECTOR: 'true'
      SCRUTINY_WEB: 'true'
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'  # Due to notifications
    proxy:
      - http_port: '{{ _port }}'

    files:
      - src: crontab
        dest: crontabs/root
        force: true
    templates:
      - src: collector.yaml
        dest: ''
        force: true
      - src: scrutiny.yaml
        dest: ''
        force: true
    volumes:
      - [ '', '/config' ]
      - '/run/udev:/run/udev:ro'

    extra:
      cpus: 0.5
      memory: 512M
      kernel_memory: 512M

      capabilities:
        - SYS_RAWIO  # is necessary to allow smartctl permission to query your device SMART data
        #- SYS_ADMIN  # is required for NVMe drives

      devices: '{{ _devices }}'
