---
# https://github.com/AnalogJ/scrutiny#docker

- name: List disks
  ansible.builtin.shell: lsblk -I 8 -d -o name,tran | grep -v usb | tail -n+2 | awk '{print "/dev/" $1 ":/dev/" $1}' | sort
  register: _devices

- set_fact:  # noqa 502
    _port: '8080'
    scrutiny_log_level: WARN  # https://github.com/sirupsen/logrus#level-logging=

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus  # Using all-in-one image due to https://github.com/AnalogJ/scrutiny/issues/573
    include_secrets: false
    log_driver: local
    env:
      GIN_MODE: release  # https://stackoverflow.com/a/48926122
    networks:
      - name: internal
      - name: unraid_docker  # Due to notifications
    proxy:
      - http_port: '{{ _port }}'

    templates:
      - src: collector.yaml
        dest: ''
        force: true
      - src: scrutiny.yaml
        dest: ''
        force: true
    volumes:
      - [ '/config', '/opt/scrutiny/config' ]
      - [ '/influxdb', '/opt/scrutiny/influxdb' ]
      - '/run/udev:/run/udev:ro'

    extra:
      cpus: 0.5
      memory: 512M
      kernel_memory: 512M

      capabilities:
        - SYS_RAWIO  # is necessary to allow smartctl permission to query your device SMART data
        #- SYS_ADMIN  # is required for NVMe drives

      devices: '{{ _devices.stdout_lines }}'
