---
# https://heimdall.site/
# https://docs.linuxserver.io/images/docker-heimdall

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: home
    image: lscr.io/linuxserver/heimdall:latest
    icon: heimdall
    log_driver: local
    service_data_dir: home
    volumes:
      - [ '/heimdall', '/config', 'rw' ]

    proxy:
      - http_port: 80

    extra:
      cpus: 0.5
      memory: 128M
      kernel_memory: 128M
