---
# https://github.com/bastienwirtz/homer

- set_fact:  # noqa 502
    _port: '8080'

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: home
    image: b4bz/homer:latest
    icon: homer
    env:
      PORT: '{{ _port }}'
    log_driver: local
    service_data_dir: home
    volumes:
      - [ '/homer', '/www/assets', 'rw' ]
      - [ '/homer/entrypoint.sh', '/entrypoint.sh', 'ro' ]

    files:
      - src: homer-entrypoint.sh
        dest: 'homer/entrypoint.sh'

    proxy:
      - http_port: '{{ _port }}'

    extra:
      cpus: 0.5
      memory: 128M
      kernel_memory: 128M
