---

# FYI: Usually this network should be created using unRAID's webGui
#      (Settings > Docker > "IPv4 custom network on interface ***").
#      Its ipam_config should reflect the network configuration set on router.

- block:
    - name: Check if external/macvlan Docker Network exists
      ansible.builtin.shell: 'docker network ls | grep {{ docker.external_network_name }}'
      register: _docker_external_network_stat
      ignore_errors: true
      changed_when: false

    - name: Create external/macvlan Docker Network
      # https://docs.ansible.com/ansible/latest/collections/community/general/docker_network_module.html
      community.docker.docker_network:
        name: '{{ docker.external_network_name }}'
        attachable: false
        driver: macvlan
        driver_options:
          parent: '{{ docker.external_network_parent }}'
        enable_ipv6: false
        internal: false
        ipam_config:
          - subnet: 10.0.100.1/24   # Subnet
            iprange: 10.0.100.0/25  # must not overlap with DHCP pool
            gateway: 10.0.100.1     # Gateway
        ipam_driver: default
        labels:
          ManagedBy: Ansible
      when: _docker_external_network_stat.rc > 0

  when: not (disable_meta_dependencies|default(false))
