---

# Remember to manually create InfluxDB database first!
# >>> CREATE DATABASE telegraf;
# >>> CREATE RETENTION POLICY one_month ON telegraf DURATION 4w REPLICATION 1 DEFAULT;

- set_fact:
    telegraf_dir: '{{ unraid.homelab_dir }}/telegraf'

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_list:
    - '{{ telegraf_dir }}'

- name: Get latest release version number
  ansible.builtin.shell:
    cmd: 'curl -s https://api.github.com/repos/influxdata/telegraf/releases/latest | jq -r .tag_name | cut -c2-'
    warn: false
  register: version
  changed_when: false

- set_fact:
    latest_version_file_path: '{{ telegraf_dir }}/telegraf-{{ version.stdout | replace(".", "") }}'

- block:
    - name: Download latest Telegraf release to /tmp
      ansible.builtin.unarchive:
        src: 'https://dl.influxdata.com/telegraf/releases/telegraf-{{ version.stdout }}_linux_amd64.tar.gz'
        remote_src: yes
        dest: /tmp
        creates: '{{ latest_version_file_path }}'
      register: _download

    - name: Copy Telegraf binary from /tmp to USB drive
      ansible.builtin.command:
        cmd: "mv '/tmp/telegraf-{{ version.stdout }}/usr/bin/telegraf' '{{ latest_version_file_path }}'"
        creates: '{{ latest_version_file_path }}'
      when: _download.changed
  always:
    - ansible.builtin.file:
        path: '/tmp/telegraf-{{ version.stdout }}'
        state: absent

- name: Copy config files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ telegraf_dir }}/{{ item }}'
    force: true
  with_list:
    - idrac.toml
    - unraid.toml
    - weather.toml

- name: Set up boot script
  ansible.builtin.blockinfile:
    content: |
      logger 'Configuring Telegraf'

      cp -vf '{{ latest_version_file_path }}' /usr/bin/telegraf
      chmod +x /usr/bin/telegraf
    dest: '{{ unraid.homelab_dir }}/boot.sh'  # unraid_prerequisites
    marker: "# {mark} ANSIBLE_TELEGRAF"

- name: Set up Supervisord config
  include_tasks: '{{ playbook_dir }}/dry/unraid/supervisor.yml'
  vars:
    name: telegraf
    programs:
      idrac:
        autorestart: true
        autostart: true
        command: /usr/bin/telegraf --config '{{ telegraf_dir }}/idrac.toml'
        killasgroup: true
        stopasgroup: true
      unraid:
        autorestart: true
        autostart: true
        command: /usr/bin/telegraf --config '{{ telegraf_dir }}/unraid.toml'
        killasgroup: true
        stopasgroup: true
      weather:
        autorestart: true
        autostart: true
        command: /usr/bin/telegraf --config '{{ telegraf_dir }}/weather.toml'
        killasgroup: true
        stopasgroup: true
