---

- set_fact:  # noqa 502
    _name: kavita

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: ebooks
    image: kizaing/kavita:latest
    icon: '{{ _name }}'
    volumes:
      - [ '/{{ _name }}', '/kavita/config', 'rw' ]
      - '{{ services.ebooks.library_volume }}:/library'

    proxy:
      - http_port: 5000

#    extra:
#      user: '{{ docker_config.default_user }}'
