---

_downloads:
  logcli-linux-amd64: 'https://github.com/grafana/loki/releases/download/{{ _install_version }}/logcli-linux-amd64.zip'
  loki-linux-amd64: 'https://github.com/grafana/loki/releases/download/{{ _install_version }}/loki-linux-amd64.zip'
  promtail-linux-amd64: 'https://github.com/grafana/loki/releases/download/{{ _install_version }}/promtail-linux-amd64.zip'
