---

- set_fact:  # noqa 502
    _name: nextcloud

# REDIS

- include_tasks: '{{ playbook_dir }}/dry/docker/redis.yml'
  vars:
    parent_container_name: '{{ _name }}'

# MAIN SERVER

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: ghcr.io/linuxserver/nextcloud
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'  # Because Nextcloud needs access to the Internet
    volumes:
      - [ '/config', '/config', 'rw' ]
      - '{{ services.nextcloud.data_dir }}:/data:rw'

    proxy:
      - http_port: 80

    extra:
      cpus: 4
      memory: 8G
      kernel_memory: 8G

- include_tasks: ./_configure_web_server.yml
  register: __configure_web_server

- include_tasks: '{{ playbook_dir }}/dry/docker/exec.yml'
  vars:
    container_name: '{{ _name }}'
    commands:
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html#id2
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html
      - occ --no-ansi --no-warnings config:system:set redis host --value='{{ redis_host }}'
      - occ --no-ansi --no-warnings config:system:set redis port --value=6379
      - occ --no-ansi --no-warnings config:system:set memcache.distributed --value='\\OC\\Memcache\\Redis'
      - occ --no-ansi --no-warnings config:system:set memcache.locking --value='\\OC\\Memcache\\Redis'
