---
# https://miniflux.app/docs/installation.html#docker

- set_fact:
    _name: podcast
    _port: 9999

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: miniflux/miniflux:latest
    icon: spotify
    command:
      - sh
      - -c
      - DATABASE_URL="$MINIFLUX_DATABASE_URL" /usr/bin/miniflux
    env:
      BASE_URL: 'https://{{ _name }}.{{ lab_domain_name }}'
      LISTEN_ADDR: '0.0.0.0:{{ _port }}'
    include_secrets: true

    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'

    proxy:
      - http_port: '{{ _port }}'

    extra:
      user: '{{ docker_config.default_user }}'
