---
# CREATE DATABASE <db_name>;
# CREATE RETENTION POLICY <name> ON <db_name> DURATION ___ REPLICATION 1 DEFAULT;

- set_fact:  # noqa 502
    _influx_config:
      cpu_cores: 4
      ramdisk_size: 1G
      bind_address:
        http: 0.0.0.0:9111
        rpc: 0.0.0.0:9112
      dir:
        data: '{{ zfs.mountpoint }}/influxdb/data'
        meta: '{{ zfs.mountpoint }}/influxdb/meta'
        wal: '{{ tmpfs.mountpoint }}/influxdb/wal'
      logging_level: debug
    _influxdb_dir: '{{ unraid.homelab_dir }}/influxdb'

- name: Get latest release version number
  ansible.builtin.shell:
    #cmd: echo "v1.8.10"
    cmd: >-
      curl -s https://api.github.com/repos/influxdata/influxdb/releases
      | jq -r 'from_entries | to_entries | .[] | select(.key[0:5] == "v1.8.") | .key'
      | head -n1
    warn: false
  register: version
  changed_when: false

- assert:  # noqa 502
    that: [ 'version.stderr | length == 0' ]
    fail_msg: "Error getting InfluxDB version: {{ version.stderr }}"

- set_fact:  # noqa 502
    latest_version_dir_path: >-
      {{ _influxdb_dir }}/influxdb-{{ version.get("stdout", "unknown")[1:] | replace(".", "") }}
    tmp_dir_path: '/tmp/influxdb-{{ version.get("stdout", "unknown")[1:] }}-1'

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_list:
    - '{{ _influxdb_dir }}'
    - '{{ latest_version_dir_path }}'

- block:
    - name: Download latest InfluxDB release to /tmp
      ansible.builtin.unarchive:
        # yamllint disable-line rule:line-length
        src: 'https://dl.influxdata.com/influxdb/releases/influxdb-{{ version.get("stdout", "unknown")[1:] }}_linux_amd64.tar.gz'  # noqa 204
        remote_src: true
        dest: /tmp
        creates: '{{ latest_version_dir_path }}/usr/bin/influx'
      register: _download
    - name: Copy InfluxDB binaries from /tmp to USB drive
      ansible.builtin.shell:
        cmd: 'cp -rf "{{ tmp_dir_path }}"/* "{{ latest_version_dir_path }}/"'
        creates: '{{ latest_version_dir_path }}/usr/bin/influx'
      when: _download.changed
  always:
    - ansible.builtin.file:  # noqa 502
        path: '{{ tmp_dir_path }}'
        state: absent

- name: Copy InfluxDB-related files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ _influxdb_dir }}/{{ item }}'
    force: true
  with_list:
    - config.toml
    - start_influxdb.sh

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install InfluxDB
    script: |
      mkdir -vp '{{ tmpfs.mountpoint }}/influxdb'
      mount -v -t tmpfs -o size={{ _influx_config.ramdisk_size }},noatime tmpfs '{{ tmpfs.mountpoint }}/influxdb'

      fromdos < "{{ _influxdb_dir }}/start_influxdb.sh" > /usr/bin/start_influxdb.sh
      chmod -v +x /usr/bin/start_influxdb.sh

      cp -ruv '{{ latest_version_dir_path }}'/* /
      cp -fv '{{ _influxdb_dir }}'/config.toml /etc/influxdb/config.toml
      rm -fv /etc/influxdb/influxdb.conf

- name: Set up Supervisord config
  include_tasks: '{{ playbook_dir }}/dry/unraid/supervisor.yml'
  vars:
    name: influxdb
    programs:
      influxdb:
        autorestart: true
        autostart: false
        command: /usr/bin/start_influxdb.sh
        killasgroup: true
        stopasgroup: true
