---

- set_fact:
    homelab_storage_dir_name: promtail
    promtail_positions_filename: '{{ unraid.services_data_dir }}/promtail/positions.yaml'
    promtail_log_level: warn  # debug, info, warn, error

- include_tasks: '{{ playbook_dir }}/dry/github_release_downloader.yml'
  vars:
    repository_name: grafana/loki
    files_to_download:
      - promtail-linux-amd64.zip
    files_to_install:
      promtail-linux-amd64: promtail
    install_on_boot: true

- name: Create directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_list:
    - '{{ unraid.services_data_dir }}/promtail'

- name: Copy files to persistent storage
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/{{ item }}'
    force: true
  with_list:
    - rc.promtail
    - promtail.config.yaml
    - syslog.promtail.conf

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Start Promtail
    script: |
      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/syslog.promtail.conf' > /etc/rsyslog.d/syslog.promtail.conf

      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/promtail.config.yaml' > /etc/promtail.config.yaml
      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/rc.promtail' > /etc/rc.d/rc.promtail
      chmod -v +x /etc/rc.d/rc.promtail

      touch '{{ promtail_positions_filename }}'
      echo > '{{ promtail_positions_filename }}'

      /etc/rc.d/rc.promtail start
      /etc/rc.d/rc.rsyslogd reload
