---

- set_fact:
    homelab_storage_dir_name: promtail
    promtail_log_level: warn  # debug, info, warn, error

- name: Create directory
  ansible.builtin.file:
    path: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}'
    state: directory

- name: Copy files to persistent storage
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/{{ item }}'
    force: true
  with_list:
    - rc.promtail
    - promtail.config.yaml
    - syslog.promtail.conf

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install Promtail
    script: |2
      latest_release="$(curl -s https://api.github.com/repos/grafana/loki/releases/latest | jq -r .tag_name)"

      mkdir -p /tmp/promtail-setup
      cd /tmp/promtail-setup
      rm -rf /tmp/promtail-setup/*

      wget "https://github.com/grafana/loki/releases/download/${latest_release}/promtail-linux-amd64.zip"
      unzip unzip promtail-linux-amd64.zip

      cp -vf ./promtail-linux-amd64 /usr/bin/promtail
      chmod -v +x /usr/bin/promtail

      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/rc.promtail' > /etc/rc.d/rc.promtail
      chmod -v +x /etc/rc.d/rc.promtail

      cd /tmp
      rm -rf /tmp/promtail-setup
