---

- set_fact:
    _port: 8080

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: bin
    image: 'docker.{{ lab_domain_name }}/microbin:1.0.2'
    icon: privatebin
    command:
      - /usr/local/bin/microbin
      - --editable
      - --hide-logo
      - --highlightsyntax
      - --wide
      - --port
      - '{{ _port | string }}'
    workdir: /app
    include_secrets: false
    log_driver: local

    networks:
      - name: '{{ docker_config.network.internal.name }}'

    volumes:
      - [ '', '/app/pasta_data', 'rw' ]

    proxy:
      - http_port: '{{ _port }}'

    extra:
      user: '{{ docker_config.default_user }}'
