---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: sqlitebrowser
    image: lscr.io/linuxserver/sqlitebrowser
    icon: sqlite
    volumes:
      - [ '', '/config', 'rw' ]
      - '{{ unraid.services_data_dir }}:/data'

    proxy:
      - http_port: 3000
