---
# Remember to manually create InfluxDB database first!
# >>> CREATE DATABASE telegraf;
# >>> CREATE RETENTION POLICY one_month ON telegraf DURATION 4w REPLICATION 1 DEFAULT;


#- https://github.com/patagonaa/prometheus-mikrotik-swos-exporter
#- https://github.com/mprasil/telegraf-snmp-mikrotik

- set_fact:
    homelab_storage_dir_name: telegraf
    promtail_log_level: warn  # debug, info, warn, error

- name: Create directory
  ansible.builtin.file:
    path: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}'
    state: directory

- name: Copy files to persistent storage
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/{{ item }}'
    force: true
  with_list:
    - rc.telegraf
    - telegraf.config.toml

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install Telegraf
    script: |2
      latest_release="$(curl -s https://api.github.com/repos/influxdata/telegraf/releases/latest | jq -r .tag_name | cut -c2-)"

      mkdir -p /tmp/telegraf-setup
      cd /tmp/telegraf-setup
      rm -rf /tmp/telegraf-setup/*

      wget "https://dl.influxdata.com/telegraf/releases/telegraf-${latest_release}_linux_amd64.tar.gz"
      tar -xvzf telegraf-*.tar.gz

      cp -vrf ./telegraf-*/* /
      chmod -v +x /usr/bin/telegraf

      fromdos < '{{ unraid.homelab_dir }}/{{ homelab_storage_dir_name }}/rc.telegraf' > /etc/rc.d/rc.telegraf
      chmod -v +x /etc/rc.d/rc.telegraf

      cd /tmp
      rm -rf /tmp/telegraf-setup
