---
# https://wiki.servarr.com/en/lidarr
# https://docs.linuxserver.io/images/docker-lidarr

- set_fact:  # noqa 502
    _volumes:
      - [ '/config', '/config' ]

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: lidarr
    image: lscr.io/linuxserver/lidarr
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'
    volumes: '{{ _volumes|list + services.servarr.library_volumes|list }}'

    proxy:
      - http_port: 8686

    extra:
      cpus: 1
      memory: 2G
      kernel_memory: 2G
