---
# https://grafana.com/docs/loki/v2.1.0/clients/promtail/configuration/
# https://github.com/grafana/loki/blob/v2.1.0/cmd/promtail/promtail-local-config.yaml

server:
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: {{ services.promtail.ingest.port.grpc }}
  http_listen_address: 0.0.0.0
  http_listen_port: {{ services.promtail.ingest.port.http }}
  log_level: {{ services.promtail.log_level }}

clients:
  - url: '{{ services.loki.ingest.url }}'

# The positions block configures where Promtail will save a file indicating how far it has read into a file.
positions:
  filename: '{{ promtail_positions_filename }}'

scrape_configs:
  - job_name: unraid
    static_configs:
      - targets:
          - 127.0.0.1
        labels:
          __path__: /var/log/*log
          job: unraid
