---
# http://supervisord.org/

- name: Install Supervisord
  ansible.builtin.shell:
    cmd: '{{ unraid.python_venv_dir }}/bin/python -m pip install supervisor'
    creates: '{{ unraid.python_venv_dir }}/bin/supervisord'

- name: Create directories for persistent files
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_list:
    - '{{ unraid.homelab_dir }}/supervisord'
    - '{{ unraid.homelab_dir }}/supervisord/supervisor.d'

- name: Copy files
  ansible.builtin.copy:
    content: '{{ lookup("template", role_path ~ "/_supervisor/" ~ item) }}'
    dest: '{{ unraid.homelab_dir }}/supervisord/{{ item }}'
    force: true
  with_list:
    - 'rc'
    - 'supervisord.conf'

- name: Install User Scripts
  include_tasks: '{{ playbook_dir }}/dry/unraid/user-script.yml'
  vars:
    name: 'supervisord_{{ item }}'
    description: '{{ item | capitalize }} Supervisord daemon'
    script: |
      #!/bin/sh
      fromdos < '{{ unraid.homelab_dir }}/supervisord/rc' > /tmp/rc.supervisord
      /bin/sh /tmp/rc.supervisord {{ item }}
      rm -f /tmp/rc.supervisord
  with_list:
    - restart
    - start
    - stop
