---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: envoyproxy
    # Log levels: [trace][debug][info][warning|warn][error][critical][off]
    command: --log-level warn --config-path /config/envoy.yaml
    image: danie1k/homelab-envoyproxy:rolling
    networks:
      - name: '{{ docker.external_network_name }}'
        ipv4_address: '{{ _reverseproxy_ip }}'
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/config', 'rw' ]

    files:
      - src: envoy/envoy.yaml
        dest: ''
