---

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: haproxy
    image: danie1k/homelab-haproxy:latest # image: clearlinux/haproxy:latest
    command:
      - "'python /docker_network_monitor/monitor.py'"
      - "'haproxy -W -db -p /var/run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg'"
    env:
      DOMAIN_NAME: '{{ lab.domain_name }}'
      HAPROXY_CONFIG_FILE: /usr/local/etc/haproxy/haproxy.cfg
      HAPROXY_PID_FILE: /var/run/haproxy.pid
      NETWORK_NAME: '{{ docker.internal_network_name }}'
    networks:
      - name: '{{ docker.external_network_name }}'
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - [ '', '/usr/local/etc/haproxy' ]

    files:
      - src: haproxy/haproxy.cfg
        dest: ''
      - src: haproxy/templates
        dest: ''
        force: true
