---

# https://doc.traefik.io/traefik/getting-started/quick-start/

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: traefik
    image: traefik:latest
    command: --configFile=/config/traefik.toml
    networks:
      - name: '{{ docker.external_network_name }}'
        ipv4_address: '{{ _reverseproxy_ip }}'
      - name: '{{ docker.internal_network_name }}'
    volumes:
      - [ '', '/config', 'rw' ]
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - '{{ lab.tls_storage_dir }}:/tls:ro'

    files:
      - src: traefik/dynamic.toml
        dest: ''
        force: true
      - src: traefik/traefik.toml
        dest: ''
        force: true
