---
# https://docs.miguelndecarvalho.pt/projects/speedtest-exporter/

- set_fact:  # noqa 502
    _name: prometheus-uptime
    _port: 9115

- name: Copy blackbox exporter config file
  ansible.builtin.copy:
    src: blackbox_exporter.yml
    dest: '{{ unraid.docker_volume_base }}/prometheus/config/blackbox_exporter.yml'
    force: true

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: prom/blackbox-exporter:latest
    command: >-
      --config.file=/config/blackbox_exporter.yml
      --history.limit=1
      --log.level=warn
      --web.listen-address=':{{ _port }}'
    networks:
      - name: '{{ docker_config.network.external.name }}'
      - name: '{{ docker_config.network.internal.name }}'
    volumes:
      - '{{ unraid.docker_volume_base }}/prometheus/config:/config:ro'

    extra:
      cpus: 0.5
      memory: 1G
      kernel_memory: 1G

- include_tasks: ../../prometheus-config.yml
  vars:
    job_name: blackbox
    job:
      metrics_path: /probe
      scrape_interval: 5s
      params:
        module: [ http_2xx ]
      static_configs:
        - targets: '{{ services.prometheus.blackbox.uptime_targets }}'
      relabel_configs:
        - source_labels: [ __address__ ]
          target_label: instance
        - source_labels: [ __address__ ]
          target_label: __param_target
          replacement: 'http://$1'
        - target_label: __address__
          replacement: '{{ _name }}.{{ docker_config.network.internal.name }}:{{ _port }}'
