---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # UNRAID
    # =======================================================
    - unraid_prerequisites
    - unraid_loki_promtail

    # =======================================================
    # DOCKER
    # =======================================================

    # Prerequisites
    - docker_internal_network
    - docker_external_network

    # Containers
    - docker_container_ldap
    - docker_container_postgresql
    - docker_container_influxdb
    - docker_container_telegraf
    - docker_container_grafana

    - docker_container_dns
    - docker_container_reverseproxy

  vars:
    _dnsmasq_ip: 172.16.100.129
    _dnsmasq_hostname: dns

    _reverseproxy_ip: 172.16.100.130
    _reverseproxy_hostname: envoy

    _static_containers:
      - grafana
      - influxdb
      - ldap
      - postgresql
      - telegraf
