---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # DOCKER
    # =======================================================

    # Prerequisites
    - docker_internal_network
    - docker_external_network

    # Containers
    - docker_container_haproxy
    - docker_container_postgresql
