---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # Prerequisites
    # =======================================================
    - prerequisites/unraid
    - prerequisites/docker_external_network
    - prerequisites/docker_internal_network

    # =======================================================
    # UNRAID
    # =======================================================
    - unraid/backups
    - services/promtail
    - services/telegraf

    # =======================================================
    # DOCKER
    # =======================================================
    - docker/reverse_proxy

    - docker/database/influxdb
    - docker/database/mysql
    - docker/database/postgresql

#    - docker_container_dns
#    - docker_container_certbot
#
#    # Databases
#    - docker_container_ldap
#    - docker_container_redis
#
#    - docker_container_grafana
#    - docker_container_prometheus
#    - docker_container_portainer
#
#    - docker_container_aria2
#    - docker_container_firefly
#    - docker_container_home
#    - docker_container_nextcloud
#    - docker_container_portainer
#    - docker_container_wiki
#
#    # =======================================================
#    # OTHER
#    # =======================================================
#
#
#  vars:
#    disable_meta_dependencies: true
#
#    _dnsmasq_ip: 10.0.100.100
#    _dnsmasq_hostname: dns
#
#    _static_containers:
#      - grafana
#      - home
#      - ldap
#      - portainer
#      - wiki
