---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # Prerequisites
    # =======================================================
    - prerequisites/unraid
    - prerequisites/docker_external_network
    - prerequisites/docker_internal_network

    # =======================================================
    # UNRAID
    # =======================================================
    - unraid/backups
    - services/promtail
    - services/telegraf

    # =======================================================
    # DOCKER
    # =======================================================
    - docker/portainer
    - docker/reverse_proxy

    - docker/database/influxdb
    - docker/database/mysql
    - docker/database/postgresql

    - docker/monitoring/grafana
    - docker/monitoring/prometheus
    - docker/monitoring/prometheus_speedtest
    # - docker/monitoring/prometheus_uptime
    - docker/monitoring/uptime_kuma

    - docker/apps/home
    - docker/apps/nextcloud
    - docker/apps/wiki

#    - docker_container_aria2
#    - docker_container_firefly
#
#  vars:
#    disable_meta_dependencies: true
