---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    - unraid_prerequisites

    # =======================================================
    # UNRAID
    # =======================================================
    - unraid_supervisor_promtail
    - unraid_loki_promtail
    - unraid_backups

    # =======================================================
    # DOCKER
    # =======================================================

    # Prerequisites
    - docker_internal_network
    - docker_external_network

    # Networking
    - docker_container_reverseproxy
    - docker_container_dns

    - docker_container_certbot

    # Databases
    - docker_container_influxdb
    - docker_container_ldap
    - docker_container_postgresql
    - docker_container_mysql
    - docker_container_redis

    - docker_container_grafana
    - docker_container_home
    - docker_container_nextcloud
    - docker_container_portainer
    - docker_container_wiki

    # =======================================================
    # OTHER
    # =======================================================
    - unraid_telegraf

  vars:
    _dnsmasq_ip: 172.16.100.129
    _dnsmasq_hostname: dns

    _postgres_ip: 10.0.100.10
    _mysql_ip: 10.0.100.11

    _influxdb_ip: 10.0.100.12
    _influxdb_url: 'http://influxdb.{{ lab.domain_name }}:9091'

    _reverseproxy_ip: 172.16.100.130
    _reverseproxy_hostname: envoy

    _static_containers:
      - grafana
      - home
      - influxdb
      - ldap
      - postgresql
      - portainer
      - wiki
