---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # Prerequisites
    # =======================================================
    - prerequisites/unraid
    - prerequisites/docker_networks

    # =======================================================
    # UNRAID
    # =======================================================
    - unraid/backups
    - services/promtail
    - services/telegraf

    # =======================================================
    # DOCKER
    # =======================================================
    - docker/portainer
    - docker/registry
    - docker/reverse_proxy
    - docker/sso

    - docker/database/influxdb
    - docker/database/mysql
    - docker/database/postgresql

    - docker/monitoring/grafana
    - docker/monitoring/prometheus
    - docker/monitoring/prometheus_speedtest
    # - docker/monitoring/prometheus_uptime
    - docker/monitoring/uptime_kuma

    - docker/apps/aria2
    - docker/apps/diagrams
    - docker/apps/home
    - docker/apps/jellyfin
    - docker/apps/nextcloud
    - docker/apps/office
    - docker/apps/torrent
    - docker/apps/wiki

    - docker/own_apps/anime_catalog

    - docker/servarr/lidarr
    # Media transcoders
    - docker/servarr/handbrake
    - docker/servarr/tdarr
    #- docker/servarr/unmanic

#    - docker_container_firefly
#
#  vars:
#    disable_meta_dependencies: true
