---

- hosts: unraid
  gather_facts: false
  vars_files:
    - defaults/vars.yml

  roles:
    # =======================================================
    # UNRAID
    # =======================================================
    - unraid_prerequisites
    - unraid_loki_promtail

    # =======================================================
    # DOCKER
    # =======================================================

    # Prerequisites
    - docker_internal_network
    - docker_external_network

    # Containers
    - docker_container_ldap
    - docker_container_postgresql

    - docker_container_reverseproxy
