---
# https://doc.traefik.io/traefik/getting-started/quick-start/

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: traefik
    image: traefik:latest
    include_secrets: true
    log_driver: local
    command: --configFile=/config/traefik.toml
    networks:
      - name: unraid_docker
        ipv4_address: '{{ services.reverse_proxy.static_ip }}'
      - name: internal
    volumes:
      - [ '', '/config', 'rw' ]
      - /var/run/docker.sock:/var/run/docker.sock:ro

    proxy:
      - http_port: 8080
        service: api@internal

    templates:
      - src: traefik/traefik.toml
        dest: ''
        force: true
      - src: traefik/dynamic.toml
        dest: ''
        force: true

    extra:
      cpus: 4
      memory: 6G
      kernel_memory: 6G
