---

- set_fact:  # noqa 502
    _scripts:
      - get_tls_from_pfsense.sh
      - reattach_docker_networks.sh
      - slow_down_idrac_fans.sh
      - update_idrac_tls.sh

- name: 'scripts : Copy files to persistent storage'
  ansible.builtin.template:
    src: '{{ role_path }}/_scripts/{{ item }}'
    dest: '{{ unraid.scripts_dir }}/{{ item }}'
    force: true
  with_list: '{{ _scripts }}'

- name: 'scripts : Copy bht script to persistent storage'
  # https://www.youtube.com/watch?v=9bh5ZK8z4ZA
  # https://github.com/ezonakiusagi/bht
  # The bht/bht script has been modified to remove email functionality
  ansible.builtin.copy:
    src: '{{ role_path }}/_scripts/bht/bht'
    dest: '{{ unraid.scripts_dir }}/bht'
    force: true

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install scripts
    script: |2
      scripts=(
        'bht'
      {% for item in _scripts %}
        '{{ item }}'
      {% endfor %}
      )

      for fname in "${scripts[@]}"
      do
        fromdos < "{{ unraid.scripts_dir }}/${fname}" > "/usr/bin/${fname}"
        chmod -v +x "/usr/bin/${fname}"
      done
