---

- set_fact:  # noqa 502
    _scripts:
      - get_tls_from_pfsense.sh
      - update_idrac_tls.sh

- name: 'scripts : Copy files to persistent storage'
  ansible.builtin.template:
    src: '{{ role_path }}/_scripts/{{ item }}'
    dest: '{{ unraid.scripts_dir}}/{{ item }}'
    force: true
  with_list: '{{ _scripts }}'

- include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Install scripts
    script: |2
      scripts=(
      {% for item in _scripts%}
        '{{ item }}'
      {% endfor %}
      )

      for fname in "${scripts[@]}"
      do
        fromdos < "{{ unraid.scripts_dir}}/${fname}" > "/usr/bin/${fname}"
        chmod -v +x "/usr/bin/${fname}"
      done
