---
# https://github.com/jgraph/docker-drawio

# unraid/secrets:
#  KEYSTORE_PASS
#  KEY_PASS

- set_fact:  # noqa 502
    _name: diagrams
    _log_level: WARNING  # SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: jgraph/drawio:alpine
    include_secrets: true
    env:
      LETS_ENCRYPT_ENABLED: 'false'
    volumes:
      - [ '/logging.properties', '/usr/local/tomcat/conf/logging.properties', 'ro' ]

    templates:
      - src: logging.properties
        dest: ''
        force: true

    proxy:
      - http_port: 8080

# https://github.com/jgraph/docker-drawio/blob/dev/nextcloud/after-install.sh

- name: Install Draw.io for Nextcloud
  include_tasks: '{{ playbook_dir }}/dry/docker/exec.yml'
  vars:
    container_name: nextcloud
    ignore_errors: true
    commands:
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html#id2
      # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html
      - occ --no-ansi --no-interaction --no-warnings app:install drawio
      - occ --no-warnings config:app:set drawio DrawioUrl --value='https://{{ _name }}.{{ lab_domain_name }}/'
