---
# https://docs.linuxserver.io/images/docker-jellyfin

- set_fact:  # noqa 502
    _name: jellyfin
    _volumes:
      - [ '/config', '/config', 'rw' ]
      - [ '/vc', '/opt/vc/lib', 'rw' ]
      - '{{ unraid.tls_storage_dir }}:/tls:ro'

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: linuxserver/jellyfin:latest
    icon: '{{ _name }}'
    env:
      JELLYFIN_PublishedServerUrl: '{{ services.jellyfin.static_ip }}'
    networks:  # WARNING! Jellyfin breaks down completely if connected to >1 network!
#      - name: '{{ docker_config.network.iot.name }}'  # IOT net, due to DLNA
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.jellyfin.static_ip }}'
    volumes: '{{ _volumes|list + services.jellyfin.media_volumes_mapping|list }}'

    files:
      - src: custom-cont-init.d
        dest: config/
        force: true

    extra:
      cpus: 4
      memory: 5G
      kernel_memory: 7G

      # https://www.youtube.com/watch?v=S4fcR4s15OI
      mounts:
        - type: tmpfs
          target: /tmp
          tmpfs_size: 10737418240  # 10 GB
