---
# https://docs.linuxserver.io/images/docker-jellyfin

- set_fact:  # noqa 502
    _name: jellyfin
    _volumes:
      - [ '/config', '/config', 'rw' ]
      - [ '/vc', '/opt/vc/lib', 'rw' ]
      - '{{ unraid.tls_storage_dir }}:/tls:ro'

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: lscr.io/linuxserver/jellyfin:latest
    webui: 'http://{{ _name }}.{{ lab_domain_name }}:8096/'
    env:
      JELLYFIN_PublishedServerUrl: '{{ services.jellyfin.static_external_ip }}'
    networks:
      - name: '{{ docker_config.network.iot.name }}'  # IOT net, due to DLNA
        ipv4_address: '{{ services.jellyfin.static_ip }}'
      - name: '{{ docker_config.network.external.name }}'
    volumes: '{{ _volumes|list + services.jellyfin.media_volumes_mapping|list }}'

    extra:
      cpus: 4
      memory: 5G
      kernel_memory: 7G

      # Remove healthcheck from container
      healthcheck:
        test: [ "NONE" ]
      # https://www.youtube.com/watch?v=S4fcR4s15OI
      mounts:
        - type: tmpfs
          target: /tmp
          tmpfs_size: 21474836480  # 20 GB
