---
# https://docs.linuxserver.io/images/docker-jellyfin

- set_fact:  # noqa 502
    _name: jellyfin
    _volumes:
      - [ '/config', '/config', 'rw' ]
      - [ '/vc', '/opt/vc/lib', 'rw' ]
      - '{{ unraid.tls_storage_dir }}:/tls:ro'

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}-server'
    image: linuxserver/jellyfin:latest
    include_secrets: false
    service_data_dir: '{{ _name }}'
    icon: '{{ _name }}'
    env:
      JELLYFIN_PublishedServerUrl: '{{ services.jellyfin.server.static_ip }}'
    networks:  # WARNING! Jellyfin breaks down completely if connected to >1 network!
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.jellyfin.server.static_ip }}'
    volumes: '{{ _volumes|list + services.jellyfin.server.media_volumes_mapping|list }}'

    files:
      - src: custom-cont-init.d
        dest: config/
        force: true

    extra:
      cpus: 4
      memory: 5G
      kernel_memory: 7G

      # https://www.youtube.com/watch?v=S4fcR4s15OI
      mounts:
        - type: tmpfs
          target: /tmp
          tmpfs_size: 10737418240  # 10 GB

# https://github.com/jellyfin/jellyfin-vue

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: jellyfin/jellyfin-vue:unstable
    include_secrets: false
    service_data_dir: '{{ _name }}'
    icon: '{{ _name }}'

    proxy:
      - http_port: 80
