---

- name: Create directory for persistent files
  ansible.builtin.file:
    path: '{{ unraid.homelab_dir }}/docker_icons'
    state: directory

- name: Copy files to persistent storage
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ unraid.homelab_dir }}/docker_icons/'
  with_list:
    - docker.png
    - docker-image.png
    - docker-image-icon.patch

- name: Copy icons to persistent storage
  ansible.builtin.copy:
    src: '{{ item[0] }}'
    dest: '/usr/local/emhttp/plugins/dynamix.docker.manager/images/{{ item[1] }}'
  with_list:
    - [ docker.png, question.png ]
    - [ docker-image.png, image.png ]

- name: Set up boot script
  ansible.builtin.blockinfile:
    content: '{{ lookup("template", role_path ~ "/other/boot_docker_icons.sh") }}'
    dest: '{{ unraid.homelab_dir }}/boot.sh'
    marker: "# {mark} ANSIBLE_DOCKER_ICONS"
