---
# https://savannah.nongnu.org/projects/hddtemp/

- name: Create persistent extra packages directory on Flash drive
  ansible.builtin.file:
    path: '/boot/extra'
    state: directory

- name: Download hddtemp packages
  ansible.builtin.get_url:
    url: https://packages.slackonly.com/pub/packages/current-x86_64/system/hddtemp/hddtemp-0.3beta15-x86_64-4_slonly.txz
    dest: /boot/extra/hddtemp.txz

- name: Install hddtemp packages
  ansible.builtin.shell:
    cmd: installpkg /boot/extra/hddtemp.txz
    creates: /usr/sbin/hddtemp

- name: Copy Slackware rc file
  ansible.builtin.copy:
    content: '{{ lookup("template", role_path ~ "/other/rc.hddtemp") }}'
    dest: '{{ unraid.homelab_dir }}/supervisord/rc.hddtemp'
    force: false

- name: Set up boot script
  ansible.builtin.blockinfile:
    content: '{{ lookup("template", role_path ~ "/other/boot_hddtemp.sh") }}'
    dest: '{{ unraid.homelab_dir }}/boot.sh'
    marker: "# {mark} ANSIBLE_HDDTEMP"
