---

- include_tasks: _persistent-storage.yml
- include_tasks: _python-virtualenv.yml

- include_tasks: _docker-icons.yml

- include_tasks: _daemonize.yml
- include_tasks: _hddtemp.yml
- include_tasks: _supervisord.yml
