---

# unraid/secrets:
#  REGISTRY_HTTP_SECRET

- set_fact:
    _config_file_path: /etc/docker/registry/config.yml
    _name: docker-registry

# https://docs.docker.com/registry/configuration

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}'
    image: registry:2
    command: '{{ _config_file_path }}'
    icon: _docker
    webui: false
    service_data_dir: '{{ _name }}'
    volumes:
      - [ '/config.yml', '{{ _config_file_path }}' ]
      - '/mnt/user/services/{{ _name }}/registry:/var/lib/registry:rw'

    files:
      - src: nginx.conf
        dest: ''
        force: true
    templates:
      - src: config.yml
        dest: ''
        force: true

    extra:
      cpus: 2
      memory: 1G
      kernel_memory: 1G
      user: '{{ docker_config.default_user }}'

# https://docs.docker.com/registry/garbage-collection/

- name: Install cron job on boot
  include_tasks: '{{ playbook_dir }}/dry/unraid/boot.yml'
  vars:
    name: Docker Registry garbage collection
    script: |
      (
        crontab -l 2>/dev/null
        echo
        echo '# Docker Registry garbage collection'
        echo '0 */12 * * * [[ "$(docker ps --filter "name=^{{ _name }}$" --format {%raw%}"{{.Names}}"{%endraw%})" == "{{ _name }}" ]] && docker exec docker-registry registry garbage-collect "{{ _config_file_path }}" >/dev/null 2>&1'
      ) | crontab -

# https://github.com/Joxit/docker-registry-ui

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: '{{ _name }}-ui'
    image: joxit/docker-registry-ui:latest
    include_secrets: false
    icon: _docker
    env:
      DELETE_IMAGES: 'true'
      NGINX_PROXY_PASS_URL: 'http://{{ _name }}.{{ docker_config.network.internal.name }}:5000'
      REGISTRY_TITLE: '{{ lab_domain_name }}'
      SINGLE_REGISTRY: 'true'
      SHOW_CONTENT_DIGEST: 'true'
    service_data_dir: '{{ _name }}'
    volumes:
      - '{{ unraid.services_data_dir }}/{{ _name }}/nginx.conf:/etc/nginx/nginx.conf:ro'

    proxy:
      - http_port: 80
        hostname: docker

    extra:
      cpus: 2
      memory: 1G
      kernel_memory: 1G
