---
# https://docs.ansible.com/ansible/latest/collections/community/general/docker_network_module.html

# Usually this network should be created using unRAID's webGui
# (Settings > Docker > "IPv4 custom network on interface ***").
# Its ipam_config should reflect the network configuration set on router.

- name: Check if 'external' Docker Network exists
  ansible.builtin.shell: 'docker network ls | grep {{ docker_config.network.external.name }}'
  register: docker_external_network_stat
  ignore_errors: true
  changed_when: false

- name: Create 'external' (macvlan) Docker Network
  community.docker.docker_network:
    name: '{{ docker_config.network.external.name }}'
    attachable: false
    driver: macvlan
    driver_options:
      parent: '{{ docker_config.network.external.parent }}'
    enable_ipv6: false
    internal: false
    ipam_config: [ '{{ docker_config.network.external.ipam_config }}' ]
    ipam_driver: default
    labels:
      ManagedBy: Ansible
  when: docker_external_network_stat.get('rc', 1) > 0


- name: Check if 'iot' Docker Network exists
  ansible.builtin.shell: 'docker network ls | grep {{ docker_config.network.iot.name }}'
  register: docker_iot_network_stat
  ignore_errors: true
  changed_when: false

- name: Create 'iot' (macvlan) Docker Network
  community.docker.docker_network:
    name: '{{ docker_config.network.iot.name }}'
    attachable: false
    driver: macvlan
    driver_options:
      parent: '{{ docker_config.network.iot.parent }}'
    enable_ipv6: false
    internal: false
    ipam_config: [ '{{ docker_config.network.iot.ipam_config }}' ]
    ipam_driver: default
    labels:
      ManagedBy: Ansible
  when: docker_iot_network_stat.get('rc', 1) > 0
