---
# https://grafana.com/docs/grafana/latest/administration/configure-docker/

# unraid/secrets:
#  GF_DATABASE_NAME
#  GF_DATABASE_USER
#  GF_DATABASE_PASSWORD


- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: grafana
    image: grafana/grafana:latest
    env:
      # https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: 'postgres.{{ docker_config.network.internal.name }}:5432'
    networks:
      - name: '{{ docker_config.network.internal.name }}'
      - name: '{{ docker_config.network.external.name }}'
        ipv4_address: '{{ services.grafana.static_ip }}'

    proxy:
      - http_port: 3000

    volumes:
      - [ '', '/var/lib/grafana' ]

    extra:
      cpus: 2
      memory: 2G
      kernel_memory: 2G
      user: '{{ docker_config.default_user }}'
