---
# https://hub.docker.com/r/tinyfilemanager/tinyfilemanager

- set_fact:  # noqa 502
    tinyfilemanager:
      http_host: 'static.{{ lab_domain_name }}'
      root_path: /config/data

- include_tasks: '{{ playbook_dir }}/dry/docker/unraid-container.yml'
  vars:
    name: static
    image: 'docker.{{ lab_domain_name }}/tinyfilemanager:latest'
    include_secrets: false
    icon: _file
    webui: false
    volumes:
      - '/mnt/user/services/static/data:{{ tinyfilemanager.root_path }}:rw'
      - [ '/config/tinyfilemanager.conf.php', '/config/www/config.php', 'ro' ]

    files:
      - src: favicon.ico
        dest: data/favicon.ico
        force: true
    templates:
      - src: tinyfilemanager.conf.php
        dest: config/tinyfilemanager.conf.php
        force: true

    proxy:
      - http_port: 80
